#!/usr/bin/env python3

import hashlib
import os
import io
import re
import sys
import getopt


MAX_BUFFER_SIZE = io.DEFAULT_BUFFER_SIZE

def generate_file_check_sum (filepath):

    file = None
    try:
        file = open (filepath, 'rb')
        hash = hashlib.new ('sha1')
        while True:
            chunk = file.read (MAX_BUFFER_SIZE)
            if not chunk:
                break
            hash.update (chunk)
    except Exception as e:
        print ('ERROR!:', e)
    else:
        return hash.hexdigest ()
    finally:
        if file is not None:
            try:
                file.close ()
            except Exception:
                pass

def main (argv=sys.argv):
    """Usage: df-finder [-e <regexp pattern>] [path...]

default path is the current directory
options:
  -e    regexp pattern for directories and files to be excluded from search
  -i    regexp pattern to include in search only specific files an directories
  --ef  same as -e but for files ONLY
  --if  same as -i but for files ONLY
  --ed  same as -e but for directories ONLY
  --id  same as -i but for directories ONLY
  -h    print this message
  -v    be verbose
  -vv   be more verbose
  -0    include empty files (why anyone want to do that?)
    """
    try:
        args, paths = getopt.gnu_getopt (argv[1:], 'he:i:v0',
                                         ['help', 'ef=', 'if=', 'ed=', 'id='])
    except getopt.GetoptError as err:
        ## print help information and exit:
        print (err, main.__doc__, sep='\n')
        sys.exit (2)

    FOLDERS = []
    VERBOSE = 0
    Z0FILES = 0
    ## regexp patterns to exclude and include only specific files AND
    ## directories
    EXCLUDE = None
    INCLUDE = None
    ## regexp patterns to exclude and include only specific files
    EXCLUDEF = None
    INCLUDEF = None
    ## regexp patterns to exclude and include only specific dirs
    EXCLUDED = None
    INCLUDED = None


    for o, a in args:
        ## print help message and exit
        if o in ('-h', '--help'):
            print (main.__doc__)
            sys.exit ()
        elif o == '-v':
            ## increase verbosity
            VERBOSE += 1
        elif o == '-0':
            ## include zero size files
            Z0FILES = 1
        elif o == '-e':
            ## compile exclude regexp pattern, do not search files
            ## that match this pattern
            EXCLUDE = re.compile (a)
        elif o == '-i':
            ## include pattern, search only for files that match it
            INCLUDE = re.compile (a)
        elif o == '--ef':
            ## compile exclude regexp pattern, do not search files
            ## that match this pattern
            EXCLUDEF = re.compile (a)
        elif o == '--if':
            ## include pattern, search only for files that match it
            INCLUDEF = re.compile (a)
        elif o == '--ed':
            ## compile exclude regexp pattern, do not search directories
            ## that match this pattern
            EXCLUDED = re.compile (a)
        elif o == '--id':
            ## include pattern, search only directories that match it
            INCLUDED = re.compile (a)

    if paths:
        for path in paths:
            ## Check if path is a valid directory
            if not os.path.exists (path):
                errmsg = 'Path "%s" do not exist'
                print (errmsg % path, file=sys.stderr)
                continue
            elif not os.path.isdir (path):
                errmsg = 'Path "%s" is not a directory'
                print (errmsg % path, file=sys.stderr)
                continue
            ## Append path to folder list we will be checking
            FOLDERS.append (path)
        ## Check if there are any valid dirs in searching path
        if not FOLDERS:
            errmsg = 'There is not a single valid location to check'
            print (errmsg, file=sys.stderr)
            sys.exit (1)
    else:
        ## if path not given, use default (current folder)
        FOLDERS.append (os.getcwd ())


    ## Duplicate files
    dfiles = {}

    try:
        for basedir in FOLDERS:
            for (dirpath, dirnames, filenames) in os.walk (basedir):
                if VERBOSE:
                    print ('checking dir:', dirpath)

                ## Omit excluded and not included directories and files,
                ## iterate over list copies to avoid problems with lists
                ## changing their size during iteration.

                ## file list to omit
                f_to_omit = []
                for file in filenames [:]:
                    if INCLUDE and not INCLUDE.match (file):
                        f_to_omit.append (file)
                    if INCLUDEF and not INCLUDEF.match (file):
                        f_to_omit.append (file)
                    if EXCLUDE and EXCLUDE.match (file):
                        f_to_omit.append (file)
                    if EXCLUDEF and EXCLUDEF.match (file):
                        f_to_omit.append (file)
                if f_to_omit:
                    if VERBOSE > 1:
                        print ('Omitting files:')
                    for f in f_to_omit:
                        filenames.remove (f)
                        if VERBOSE > 1:
                            print (' ', f)

                ## folder list to omit
                d_to_omit = []
                for dir in dirnames [:]:
                    if INCLUDE and not INCLUDE.match (dir):
                        d_to_omit.append (dir)
                    if INCLUDED and not INCLUDED.match (dir):
                        d_to_omit.append (dir)
                    if EXCLUDE and EXCLUDE.match (dir):
                        d_to_omit.append (dir)
                    if EXCLUDED and EXCLUDED.match (dir):
                        d_to_omit.append (dir)
                if d_to_omit:
                    if VERBOSE > 1:
                        print ('Omitting dirs:')
                    for d in d_to_omit:
                        dirnames.remove (d)
                        if VERBOSE > 1:
                            print (' ', d)

                try:
                    if VERBOSE > 1:
                        print ('Files to check:')

                    for i, file in enumerate (filenames):
                        path = os.path.join (dirpath, file)
                        if os.path.islink (path):
                            continue

                        stat = os.stat (path)
                        ## check for non empty files only,
                        ## unless Z0FILES option is set
                        if not Z0FILES and stat.st_size == 0:
                            continue

                        if VERBOSE > 1:
                            print (' ', os.path.basename (path))
                        ## generate file hash
                        hash = generate_file_check_sum (path)

                        entry = (path, stat)
                        if hash in dfiles:
                            dfiles [hash].append (entry)
                        else:
                            dfiles [hash] = [entry]
                except (OSError, IOError) as err:
                    print (err, file=sys.stderr)

    except KeyboardInterrupt:
        print ('Canceled!')
    finally:
        print ()
        for k, v in dfiles.items ():
            if len (v) > 1:
                print ('SHA1:', k)
                print ('size:', v [0][1].st_size)
                print ('-' * 79)
                for entry in v:
                    path, name = os.path.split (entry [0])
                    print ('  file name:', name)
                    print ('  file path:', path)
                    print ()
                print ('=' * 79)

if __name__ == "__main__":
    main ()
